# Generated by Django 5.1.6 on 2025-02-27 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiposts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorys', models.ManyToManyField(related_name='trip', to='apiposts.tripcategorymodel')),
            ],
        ),
    ]
